services:
    novemberfive_logging.monolog.formatter:
        class: NovemberFive\LoggingBundle\Formatter\NovemberFiveFormatter
        arguments: [ '%kernel.environment%']

    novemberfive_logging.processor.session_request:
        class: NovemberFive\LoggingBundle\Processor\SessionRequestProcessor
        arguments:  ['@session', '@security.token_storage', '%novemberfive_logging.log_session_token%']
        tags:
            - { name: monolog.processor, method: processRecord }

    novemberfive_logging.processor.request_id:
        class: NovemberFive\LoggingBundle\Processor\RequestIdProcessor
        arguments:  ['@request_stack', '%novemberfive_logging.request_id_header%']
        tags:
            - { name: monolog.processor, method: processRequest }
